# Generated by Django 4.0 on 2021-12-14 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operatings',
            fields=[
                ('OperatingId', models.AutoField(primary_key=True, serialize=False)),
                ('OperatingName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('ParcelId', models.AutoField(primary_key=True, serialize=False)),
                ('ParcelName', models.CharField(max_length=100)),
                ('ParcelSurface', models.CharField(max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('OperatingName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcels.operatings')),
            ],
        ),
    ]
